name: Batch Sync Resume Images to Aliyun ACR

on:
  workflow_dispatch:

jobs:
  sync-all:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Aliyun ACR
        uses: docker/login-action@v3
        with:
          registry: crpi-o8thnhvwfkexpji6.cn-shenzhen.personal.cr.aliyuncs.com
          username: ${{ secrets.ALIYUN_USERNAME }}
          password: ${{ secrets.ALIYUN_PASSWORD }}

      - name: 1. Sync Postgres (数据库)
        run: |
          docker pull postgres:15-alpine
          docker tag postgres:15-alpine crpi-o8thnhvwfkexpji6.cn-shenzhen.personal.cr.aliyuncs.com/my-docker-proxy-2026/resume-postgres:latest
          docker push crpi-o8thnhvwfkexpji6.cn-shenzhen.personal.cr.aliyuncs.com/my-docker-proxy-2026/resume-postgres:latest

      - name: 2. Sync Chrome (官方推荐轻量级打印机)
        run: |
          docker pull chromedp/headless-shell:latest
          docker tag chromedp/headless-shell:latest crpi-o8thnhvwfkexpji6.cn-shenzhen.personal.cr.aliyuncs.com/my-docker-proxy-2026/resume-chrome:latest
          docker push crpi-o8thnhvwfkexpji6.cn-shenzhen.personal.cr.aliyuncs.com/my-docker-proxy-2026/resume-chrome:latest

      - name: 3. Sync App (最新版前后端合并主程序)
        run: |
          docker pull amruthpillai/reactive-resume:latest
          docker tag amruthpillai/reactive-resume:latest crpi-o8thnhvwfkexpji6.cn-shenzhen.personal.cr.aliyuncs.com/my-docker-proxy-2026/resume-app:latest
          docker push crpi-o8thnhvwfkexpji6.cn-shenzhen.personal.cr.aliyuncs.com/my-docker-proxy-2026/resume-app:latest
